### PR TITLE
chore: eslint and update dependencies

### PR DESCRIPTION
**Pull request by piuccio**
Add linting and fix indentation.

I've also updated all dependencies except express, most of them are only used in tests, the others are only minor updates.

@tombburnell @WebReflection

### CODE REVIEW

**Comment by WebReflection** [comment]
good stuff, but I am not sure I've mentioned before, we are trying to have same versioning per each repository so that whenever we'll manage to switch to npm 3 or yarn we can have all of them downloaded once and shared, instead of per each folder.

TL;DR can we update others repositories too? 😄

**Comment by piuccio** [comment]
> can we update others repositories too?

yes, slowly 😆

**Comment by piuccio** [comment]
checks are now green, somehow `eslint` doesn't work on node `0.10`

**Comment by WebReflection** [comment]
P.S. I once created this utility to diff packages within different folders
https://gist.github.com/WebReflection/18aa7b2ea9075b910e3cf57f5d814a5a

**Pull request merged**
